#!/bin/bash 

echo "This report is Generated by Juan Cortes - Student ID: 200553559"

echo "User: $(whoami), Date and Time: $(date)"

echo    # Blank line

echo "
System Information
======================================"
echo "Hostname: " ; Hostname
echo "OS: " ; lsb_release -a

echo "Uptime: " ; uptime

echo    # Blank line

echo " 
Hardware Information
======================================"

echo "CPU: "; lshw -class cpu -short
echo "Speed: "; cat /proc/cpuinfo | grep Hz
echo "Ram: " ; lshw -short -C memory
echo "Disk(s): "; lsblk -d -o NAME,MODEL
echo "Video: " ; lspci | grep VGA

echo    # Blank line

echo "
Network Information
========================================"
echo "FQDN: " ; domainname
echo "Host: " ; hostname -I
echo "Gateway IP: " ; ip route | grep -Eo 'via \S+' | awk '{print $2}'

echo "DNS Server: " ; cat /etc/resolv.conf

echo "InterfaceName: " ; ip -o link show | awk -F ': ' '{print $2}'


echo "IP Address: " ; ip a s ens33 | grep -w inet

echo    # Blank line
echo "
System Status
================================"

echo "Users Logged In: "; who
echo "Disk Space: " ; df -h | awk '$1 ~ /^\/dev/ {print $6, $4}'

echo "Process Count: " ; ps aux | wc -l

echo "Load Averages: " ; w
echo "Memory Allocation: " ; free -m
echo "Listening Network Ports: " ; ss -tuln

echo "UFW Rules: " ; sudo ufw status
